services:

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "${ZK_PORT}:${ZK_PORT}"
    networks:
      - cli-tool
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:3.6
    container_name: kafka
    ports:
      - "${KAFKA_PORT}:${KAFKA_PORT}"
    networks:
      - cli-tool
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:${ZK_PORT}
      - KAFKA_CFG_LISTENERS=INTERNAL://:29092,EXTERNAL://:${KAFKA_PORT}
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:29092,EXTERNAL://localhost:${KAFKA_PORT}
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper

  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: redpanda-console
    ports:
      - "${KAFKA_UI_PORT}:8080"
    networks:
      - cli-tool
    environment:
      - KAFKA_BROKERS=kafka:29092
    depends_on:
      - kafka

networks:
  cli-tool:
